server:
  port: 8071
logging:
  level:
    root: WARN
    com.tananushka.resource.svc: INFO
    com.tananushka.resource.svc.service.ResourceService: INFO
spring:
  application:
    name: "resource-svc"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5471}/resource_svc_db"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    show-sql: false
  activemq:
    broker-url: "tcp://${ACTIVEMQ_HOST:localhost}:61616"
    user: "${ACTIVEMQ_USERNAME}"
    password: "${ACTIVEMQ_PASSWORD}"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
queue:
  resource: "resource.queue"
svc:
  song-svc:
    name: "SONG-SVC"
    songs-endpoint: "/songs"
    health-endpoint: "/song-svc/health"
  storage-svc:
    name: "STORAGE-SVC"
    storages-endpoint: "/storages"
    health-endpoint: "/storage-svc/health"
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5 # Time between heartbeats
    leaseExpirationDurationInSeconds: 5 # Time before lease expires
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: db, externalApi
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
      path-mapping:
        health: resource-svc/health
cloud:
  aws:
    endpoint: "${AWS_ENDPOINT_URL:http://localhost:4566}"
    region: us-east-1
    credentials:
      accessKey: "${AWS_ACCESS_KEY}"
      secretKey: "${AWS_SECRET_KEY}"
retry:
  maxAttempts: 10
  delay: 1000
  multiplier: 2.0
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true  # Enable health indicators for monitoring
        slidingWindowSize: 5  # Number of calls considered for circuit breaker decisions
        failureRateThreshold: 30  # Percentage of failures required to open the circuit
        waitDurationInOpenState: 5s  # Time the circuit stays open before moving to half-open
        permittedNumberOfCallsInHalfOpenState: 2  # Number of calls allowed in half-open state
        slidingWindowType: COUNT_BASED  # Type of sliding window (COUNT_BASED or TIME_BASED)
        minimumNumberOfCalls: 5  # Minimum number of calls required before calculating error rate
    instances:
      storageSvcClient:
        baseConfig: default