server:
  port: 8072
logging:
  level:
    root: WARN
    com.tananushka.song.svc: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  config: classpath:logback.xml
spring:
  application:
    name: "song-svc"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5472}/song_svc_db"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: db
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        health: song-svc/health
  prometheus:
    metrics:
      export:
        enabled: true