{
 "title": "Microservices Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_used_bytes{area=\"heap\"}) / sum by(instance) (jvm_memory_max_bytes{area=\"heap\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Gateway Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri!~\".*actuator.*\", uri!~\".*health.*\", uri!~\".*prometheus.*\", uri!=\"UNKNOWN\", uri!=\"REDIRECTION\"}[5m]) / rate(http_server_requests_seconds_count{uri!~\".*actuator.*\", uri!~\".*health.*\", uri!~\".*prometheus.*\",  uri!=\"UNKNOWN\", uri!=\"REDIRECTION\"}[5m])",
     "legendFormat": "{{instance}} - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Idle Database Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (application, pool) (hikaricp_connections_idle)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Active Database Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (application, pool) (hikaricp_connections_active)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Max Database Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (application, pool) (hikaricp_connections_max)",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}