#FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu
FROM openjdk:17-alpine
WORKDIR /app
#RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN apk update && apk add --no-cache curl
COPY target/eureka-svc-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8761
CMD ["java", "-jar", "app.jar"]
