global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'spring-actuator'
    metrics_path: '/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'eureka-server:8761', 'gateway-svc:8070', 'song-svc:8072', 'storage-svc:8074', 'resource-svc:8071', 'resource-proc:8073' ]