server:
  port: 8761
logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka.server: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  config: classpath:logback.xml
spring:
  application:
    name: "eureka-server"
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}"
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        health: eureka-svc/health
  prometheus:
    metrics:
      export:
        enabled: true
