server:
  port: 8070
logging:
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  config: classpath:logback.xml
spring:
  application:
    name: "gateway-svc"
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-svc
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-svc
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-svc
          predicates:
            - Path=/storages/**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /grafana
        - id: kibana
          uri: http://kibana:5601
          predicates:
            - Path=/kibana/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
            #            - RewritePath=/kibana/(?<segment>.*), /${segment}
            - AddRequestHeader=X-Forwarded-Prefix, /kibana
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:9090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        health: gateway-svc/health
  prometheus:
    metrics:
      export:
        enabled: true
