server:
  port: 8070
spring:
  application:
    name: "gateway-svc"
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-svc
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-svc
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-svc
          predicates:
            - Path=/storages/**
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
      path-mapping:
        health: gateway-svc/health