logging:
  level:
    root: INFO
svc:
  song-svc:
    name: "SONG-SVC"
    songs-endpoint: "/songs"
    health-endpoint: "/song-svc/health"
cloud:
  aws:
    endpoint: "${AWS_ENDPOINT_URL:http://localhost:4566}"
    region: us-east-1
    s3:
      bucket: resource-bucket
    credentials:
      accessKey: "${AWS_ACCESS_KEY}"
      secretKey: "${AWS_SECRET_KEY}"
