server:
  port: 8073
logging:
  level:
    root: WARN
    org.springframework.retry: INFO
    com.tananushka.resource.proc.service: INFO
    com.tananushka.resource.proc.service.ResourceProcessorService: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  config: classpath:logback.xml
spring:
  application:
    name: "resource-proc"
  activemq:
    broker-url: "tcp://${ACTIVEMQ_HOST:localhost}:61616"
    user: "${ACTIVEMQ_USERNAME}"
    password: "${ACTIVEMQ_PASSWORD}"
queue:
  resource: "resource.queue"
svc:
  song-svc:
    name: "SONG-SVC"
    songs-endpoint: "/songs"
    health-endpoint: "/song-svc/health"
  resource-svc:
    name: "RESOURCE-SVC"
    resources-endpoint: "/resources/audiodata"
    health-endpoint: "/resource-svc/health"
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
retry:
  maxAttempts: 10
  delay: 1000
  multiplier: 2.0
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /
      path-mapping:
        health: resource-proc/health
  prometheus:
    metrics:
      export:
        enabled: true